"""create parties table

Revision ID: 722174be02b5
Revises: ffdc0a98111c
Create Date: 2021-03-02 17:05:25.249087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '722174be02b5'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('party_name', sa.String(length=300), nullable=False),
    sa.Column('party_size', sa.Integer(), nullable=False),
    sa.Column('open_to_request', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    op.drop_table('parties')
    # ### end Alembic commands ###
