"""empty message

Revision ID: 63304d1b044a
Revises: 78fca5d2d5fb
Create Date: 2021-03-04 15:57:24.942093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63304d1b044a'
down_revision = '78fca5d2d5fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('party_users',
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('party_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('party_users')
    # ### end Alembic commands ###
